# Tomcat
server:
  # 端口号
  port: 8080
  tomcat:
    uri-encoding: UTF-8
    threads:
      max: 1000
      min-spare: 30
    # 超时时间
    connection-timeout: 5000

#开放端点用于SpringBoot Admin的监控
management:
  health:
    rabbit:
      # 是否检测rabbit
      enabled: false
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  boot:
    admin:
      client:
        url: http://localhost:9999
  # RabbitMQ设置
  rabbitmq:
    # 访问地址
    host: 127.0.0.1
    # 端口
    port: 5672
    # 用户名
    username: guest
    # 密码
    password: guest
    # 监听设置
    listener:
      # 生产者
      direct:
        # 自动启动开关
        auto-startup: false
      # 消费者
      simple:
        # 自动启动开关
        auto-startup: false

  application:
    # 应用名称。如果启用nacos，此值必填
    name: convertVideo
  cloud:
    # Nacos的配置。
    # 如果启用Nacos服务作为配置中心，
    # 则此部分之后的内容均可以在Nacos配置中心中管理，
    # 不必在此配置文件中维护。
    nacos:
      config:
        # 配置服务地址
        server-addr: 127.0.0.1:8848
        # 启用状态
        enabled: false
      discovery:
        # 服务发现服务地址
        server-addr: 127.0.0.1:8848
        # 启用状态
        enabled: false


# log4j2设置
logging:
  level:
    root: info
    com.thinkdifferent: debug
    de.codecentric.boot.admin.client: error
  file:
    name: logs/application.log

# 线程设置参数 #######
ThreadPool:
  # 核心线程数10：线程池创建时候初始化的线程数
  CorePoolSize: 10
  # 最大线程数20：线程池最大的线程数，只有在缓冲队列满了之后才会申请超过核心线程数的线程
  MaxPoolSize: 20
  # 缓冲队列200：用来缓冲执行任务的队列
  QueueCapacity: 200
  # 保持活动时间60秒
  KeepAliveSeconds: 60
  # 允许线程的空闲时间60秒：当超过了核心线程出之外的线程在空闲时间到达之后会被销毁
  AwaitTerminationSeconds: 60


# 本服务设置
convert:
  # 重试功能需启用MQ才有效
  retry:
    # 最大重试次数（0-8）, 0标识不重试, 若异常情况只记录日志， 大于1（最大8）：标识失败进行重试的次数, 将会在以下时间重试（5min, 10min, 30min, 1h, 2h, 4h, 8h, 16h）
    max: 3
  video:
    # 接收的输入文件存储的临时文件夹
    inPutTempPath: D:/cvtest/temp/
    # 输出文件所在文件夹
    outPutPath: D:/cvtest/
    # ffmpeg相关设置
    ffmpeg:
      # ffmpeg所在文件夹和文件名
      file: C:/Program Files (x86)/FormatFactory/ffmpeg.exe
      # 可以使用的CPU进程数量。设置为0，则使用全部CPU资源
      threads: 0
      # 视频编码格式。设置为空，则默认使用libx264编码
      videoCode:
      # 帧率。设置为0，则使用原视频的帧率
      fps: 0
      # 分辨率。如：640*480。设置为空，则使用原视频的分辨率
      resolution:
      # 音频编码格式。设置为空，则默认使用aac编码
      audioCode:
      # 图片水印设置
      picMark:
        # 水印图片位置
        picFile: d:/cvtest/watermark.png
        # 水印位置。第一个参数表示水印距离视频左边的距离，第二个参数表示水印距离视频上边的距离
        overlay: 500:500
        # 水印缩放参数。缩放后的width和height
        scale: 100:100
      # 文字水印设置
      textMark:
        # 字体文件位置
        fontFile: simhei.ttf
        # 水印文字内容
        text: XX公司
        # 水印横坐标
        localX: 100
        # 水印纵坐标
        localY: 10
        # 文字大小
        fontSize: 24
        # 文字颜色
        fontColor: yellow
